### ISSUE TITLE
Error: Non-accessible chat

### ISSUE THREAD

**Issue by keuwey** [apenasrr/clonechat#19]
This happens sometimes. Sometimes it works fine, but sometimes this error appears. I've checked several times to see if the chat id is correct. And it is! I don't know what is possibly wrong.
![2023-04-01_13h01_45](https://user-images.githubusercontent.com/73517606/229301873-562ffdeb-048d-4fdd-9f90-303c60eba294.png)

**Comment by corujoraphael** [comment]
Same here
