### ISSUE TITLE
unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by denzardten** [apenasrr/clonechat#4]
useraccount = pyrogram.Client(
TypeError: __init__() got an unexpected keyword argument 'name'

**Comment by apenasrr** [comment]
Você está com uma versão desatualizada do pyrogram. Execute o arquivo updatelibs.bat

**Comment by denzardten** [comment]
i run it... maybe i need to use the latest python version?

**Comment by upolar** [comment]
> i run it... maybe i need to use the latest python version?

Which python version are u using? 

Can u verify your pyrogram version? 

`pip show pyrogram`

Mine is Pyrogram 2.0.35 and TgCrypto 1.2.3.

**Comment by denzardten** [comment]
its working now..i just updated my python to the latest version

**Comment by upolar** [comment]
Perfect.
