### ISSUE TITLE
How to support the following format,like multiple origin channels

### ISSUE THREAD

**Issue by despacito008** [apenasrr/clonechat#8]
Example: python clonechat.py --orig=-100222222,-100222654,-100265465 --dest=-10011111111

**Comment by upolar** [comment]
Try something like this:

```
python clonechat.py --orig=-100222222 --dest=-10011111111 && python clonechat.py --orig=-100222654 --dest=-10011111111 && python clonechat.py --orig=-100265465 --dest=-10011111111
```

**Comment by despacito008** [comment]
> Try something like this:
> 
> ```
> python clonechat.py --orig=-100222222 --dest=-10011111111 && python clonechat.py --orig=-100222654 --dest=-10011111111 && python clonechat.py --orig=-100265465 --dest=-10011111111
> ```

I tried. The program will continue to execute the first command until the end, and then execute the second task
